DROP table WorkItem If EXISTS;

create table WorkItem (
	id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 , INCREMENT BY 1) NOT NULL,
	name VARCHAR(100),
	description VARCHAR(100),
	status VARCHAR(100),
	PRIMARY KEY(id)

);
